
export const UNSPLASH_PROFILE_SUCCESS_ACTION = "UNSPLASH_PROFILE_SUCCESS_ACTION";
export const UNSPLASH_ADD_SUCCESS_ACTION = "UNSPLASH_ADD_SUCCESS_ACTION";
export const UNSPLASH_TOGGLELIKE_SUCESS_ACTION = "UNSPLASH_TOGGLELIKE_SUCESS_ACTION";
export const CLICK_CLOSE_ACTION = "CLICK_CLOSE_ACTION";
export const IS_LOADING_ACTION = "IS_LOADING_ACTION";
export const CLICK_PREVIEW_ACTION = 'CLICK_PREVIEW_ACTION';

